function generateCustomHeaders(parsedUrl = new URL("https://google.com")) {
    const customHeaders = {
        ":method": "POST",
        ":authority": parsedUrl.hostname + ":443",
        ":path": parsedUrl.path + "?" + randstr(6) + "=" + randstr(15),
        ":scheme": "https",
        "origin": "https://" + parsedUrl.hostname + ":443",
        "Via": "1.1 " + parsedUrl.hostname + ":443",
        "Sec-Websocket-Key": generateSecWebSocketKey(),
        "Sec-Websocket-Version": 13,
        "X-Forwarded-For": spoofedIp,
        "X-Forwarded-Host": spoofedIp,
        "X-Forwarded-Proto": "https",
        "Client-IP": spoofedIp,
        "Real-IP": spoofedIp,
        "Referer": recipes.refers,
        "CF-Connecting-IP": spoofedIp,
        "CF-RAY": randstr(10),
        "CF-Visitor": "{'scheme':'https'}",
        "cache-control": "no-cache",
        "sec-ch-ua": '"Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": recipes.platform,
        "accept-language": recipes.langHeader,
        "accept-encoding": recipes.encodingHeader,
        "upgrade-insecure-requests": "1",
        "accept": recipes.acceptHeader,
        "user-agent": recipes.mozilla + recipes.userAgentL + "-(GoogleBot + http://www.google.com)" + " Code:" + randstr(7),
        "sec-fetch-mode": "navigate",
        "sec-fetch-dest": recipes.dest,
        "sec-fetch-user": "?1",
        "sec-fetch-site": recipes.site,
        "TE": "trailers",
        "cookie": "cf_clearance=" + randstr(4) + "." + randstr(20) + "." + randstr(40) + "-0.0.1 " + randstr(20) + ";_ga=" + randstr(20) + ";_gid=" + randstr(15),
        "x-requested-with": "XMLHttpRequest",
        "GET": " / HTTP/2",
        "Max-forwards": "10",
        "pragma": "no-cache",
        "Alt-Svc": "http/2=" + parsedUrl.hostname + ":443; ma=7200",
        "cf-cache-status": "BYPASS"
    };
    return customHeaders;    
}

function randstr(length) {
    const characters =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let result = "";
    const charactersLength = characters.length;
    for (let i = 0; i < length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
}

function randomInRange(min, max) {
    return Math.floor(Math.random() * (max - min) + min);
}

function randomElement(elements) {
    return elements[randomInRange(0, elements.length)];
}

function ipSpoofing() {
    const randomByte = () => Math.floor(Math.random() * 256);
    const ip = Array.from({ length: 4 }, randomByte).join(".");
    return ip;
}

function generateSecWebSocketKey() {
    const keyLength = 16;
    const charSet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';

    let key = '';
    for (let i = 0; i < keyLength; i++) {
        const randomIndex = randomInRange(0, charSet.length);
        key += charSet.charAt(randomIndex);
    }

    const base64Key = Buffer.from(key).toString('base64');

    return base64Key;
}

function rateHeadersGenerator(type) {
    const headers = {
        1: [{ "akamai-origin-hop": randstr(5) }, { "source-ip": randstr(5) }, { "via": randstr(5) }, { "cluster-ip": randstr(5) }, { "Access-Control-Request-Method": "GET" }],
        2: [{ "akamai-origin-hop": randstr(5) }, { "source-ip": randstr(5) }, { "via": randstr(5) }, { "cluster-ip": randstr(5) }, { "X-Forwarded-For": ipSpoofing() }]
    };
    return headers[type];
}

const recipeList = {
    sigAlgorithm: [
        "ecdsa_secp256r1_sha256",
        "ecdsa_secp384r1_sha384",
        "ecdsa_secp521r1_sha512",
        "rsa_pss_rsae_sha256",
        "rsa_pss_rsae_sha384",
        "rsa_pss_rsae_sha512",
        "rsa_pkcs1_sha256",
        "rsa_pkcs1_sha384",
        "rsa_pkcs1_sha512"
    ],
    cipher: [
        "ECDHE-ECDSA-AES128-GCM-SHA256",
        "ECDHE-ECDSA-CHACHA20-POLY1305",
        "ECDHE-RSA-AES128-GCM-SHA256",
        "ECDHE-RSA-CHACHA20-POLY1305",
        "ECDHE-ECDSA-AES256-GCM-SHA384",
        "ECDHE-RSA-AES256-GCM-SHA384",
        "ECDHE-RSA-AES128-GCM-SHA256",
        "ECDHE-RSA-AES256-GCM-SHA384",
        "ECDHE-ECDSA-AES256-GCM-SHA384",
        "ECDHE-ECDSA-AES128-GCM-SHA256",
        'RC4-SHA:RC4:ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
        'ECDHE-RSA-AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
        'ECDHE:DHE:kGOST:!aNULL:!eNULL:!RC4:!MD5:!3DES:!AES128:!CAMELLIA128:!ECDHE-RSA-AES256-SHA:!ECDHE-ECDSA-AES256-SHA',
        'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
        "ECDHE-RSA-AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM",
        "ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!AESGCM:!CAMELLIA:!3DES:!EDH",
        "AESGCM+EECDH:AESGCM+EDH:!SHA1:!DSS:!DSA:!ECDSA:!aNULL",
        "EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5",
        "HIGH:!aNULL:!eNULL:!LOW:!ADH:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS",
        "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK",
        'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK',
        'ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!AESGCM:!CAMELLIA:!3DES:!EDH',
        'ECDHE-RSA-AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
        'EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5',
        'HIGH:!aNULL:!eNULL:!LOW:!ADH:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS',
        'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK',
        'RC4-SHA:RC4:ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
        'ECDHE-RSA-AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
        'ECDHE:DHE:kGOST:!aNULL:!eNULL:!RC4:!MD5:!3DES:!AES128:!CAMELLIA128:!ECDHE-RSA-AES256-SHA:!ECDHE-ECDSA-AES256-SHA',
        'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
        "ECDHE-RSA-AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM",
        "ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!AESGCM:!CAMELLIA:!3DES:!EDH",
        "AESGCM+EECDH:AESGCM+EDH:!SHA1:!DSS:!DSA:!ECDSA:!aNULL",
        "EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5",
        "HIGH:!aNULL:!eNULL:!LOW:!ADH:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS",
        "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK",
        'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK',
        'ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!AESGCM:!CAMELLIA:!3DES:!EDH',
        'ECDHE-RSA-AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
        'ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!AESGCM:!CAMELLIA:!3DES:!EDH',
        'EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5',
        'HIGH:!aNULL:!eNULL:!LOW:!ADH:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS',
        'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK',
        'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
        ':ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK',
        'RC4-SHA:RC4:ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
        'ECDHE-RSA-AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
        'ECDHE-RSA-AES256-SHA:AES256-SHA:HIGH:!AESGCM:!CAMELLIA:!3DES:!EDH',
        "ECDHE-RSA-AES128-GCM-SHA256",
        "ECDHE-RSA-AES256-GCM-SHA384",
        "ECDHE-ECDSA-AES256-GCM-SHA384",
        "ECDHE-ECDSA-AES128-GCM-SHA256"
    ],
    acceptHeader: [
        "*/*",
        "image/*",
        "image/webp,image/apng",
        "text/html",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,en-US;q=0.5",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,en;q=0.7",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/atom+xml;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/rss+xml;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/json;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/ld+json;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/xml-dtd;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/xml-external-parsed-entity;q=0.9",
        "text/html; charset=utf-8",
        "application/json, text/plain, */*",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,text/xml;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,text/plain;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "*/*",
        "image/*",
        "image/webp,image/apng",
        "text/html",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language: en-US,en;q=0.5",
        "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0",
        "Connection: keep-alive",
        "Referer: https://www.example.com",
        "Upgrade-Insecure-Requests: 1",
        "DNT: 1",
        "Accept-Encoding: gzip, deflate, br",
        "Cache-Control: max-age=0",
        "Host: www.example.com",
        "Origin: https://www.example.com",
        "Content-Type: application/x-www-form-urlencoded",
        "Content-Length: 42",
        "Cookie: session_id=abc123; user_id=12345",
        "If-None-Match: \"686897696a7c876b7e\"",
        "X-Requested-With: XMLHttpRequest",
        "X-Forwarded-For: 192.168.1.1",
        "CF-Challenge: captcha-challenge-header",
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9,application/json",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9,application/json,application/xml",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9,application/json,application/xml,application/xhtml+xml",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9,application/json,application/xml,application/xhtml+xml,text/css",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9,application/json,application/xml,application/xhtml+xml,text/css,text/javascript",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9,application/json,application/xml,application/xhtml+xml,text/css,text/javascript,application/javascript",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json,application/xml",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json,application/xml,application/xhtml+xml",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json,application/xml,application/xhtml+xml,text/css",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json,application/xml,application/xhtml+xml,text/css,text/javascript",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json,application/xml,application/xhtml+xml,text/css,text/javascript,application/javascript",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json,application/xml,application/xhtml+xml,text/css,text/javascript,application/javascript,application/xml-dtd",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json,application/xml,application/xhtml+xml,text/css,text/javascript,application/javascript,application/xml-dtd,text/csv",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/x-www-form-urlencoded,text/plain,application/json,application/xml,application/xhtml+xml,text/css,text/javascript,application/javascript,application/xml-dtd,text/csv,application/vnd.ms-excel",
    ],
    langHeader: [
        "ko-KR",
        "en-US",
        "zh-CN",
        "zh-TW",
        "ja-JP",
        "en-GB",
        "en-AU",
        "en-GB,en-US;q=0.9,en;q=0.8",
        "en-GB,en;q=0.5",
        "en-CA",
        "en-UK, en, de;q=0.5",
        "en-NZ",
        "en-GB,en;q=0.6",
        "en-ZA",
        "en-IN",
        "en-PH",
        "en-SG",
        "en-HK",
        "en-GB,en;q=0.8",
        "en-GB,en;q=0.9",
        " en-GB,en;q=0.7",
        "en-US,en;q=0.9",
        "en-GB,en;q=0.9",
        "en-CA,en;q=0.9",
        "en-AU,en;q=0.9",
        "en-NZ,en;q=0.9",
        "en-ZA,en;q=0.9",
        "en-IE,en;q=0.9",
        "en-IN,en;q=0.9",
        "ar-SA,ar;q=0.9",
        "az-Latn-AZ,az;q=0.9",
        "be-BY,be;q=0.9",
        "bg-BG,bg;q=0.9",
        "bn-IN,bn;q=0.9",
        "ca-ES,ca;q=0.9",
        "cs-CZ,cs;q=0.9",
        "cy-GB,cy;q=0.9",
        "da-DK,da;q=0.9",
        "de-DE,de;q=0.9",
        "el-GR,el;q=0.9",
        "es-ES,es;q=0.9",
        "et-EE,et;q=0.9",
        "eu-ES,eu;q=0.9",
        "fa-IR,fa;q=0.9",
        "fi-FI,fi;q=0.9",
        "fr-FR,fr;q=0.9",
        "ga-IE,ga;q=0.9",
        "gl-ES,gl;q=0.9",
        "gu-IN,gu;q=0.9",
        "he-IL,he;q=0.9",
        "hi-IN,hi;q=0.9",
        "hr-HR,hr;q=0.9",
        "hu-HU,hu;q=0.9",
        "hy-AM,hy;q=0.9",
        "id-ID,id;q=0.9",
        "is-IS,is;q=0.9",
        "it-IT,it;q=0.9",
        "ja-JP,ja;q=0.9",
        "ka-GE,ka;q=0.9",
        "kk-KZ,kk;q=0.9",
        "km-KH,km;q=0.9",
        "kn-IN,kn;q=0.9",
        "ko-KR,ko;q=0.9",
        "ky-KG,ky;q=0.9",
        "lo-LA,lo;q=0.9",
        "lt-LT,lt;q=0.9",
        "lv-LV,lv;q=0.9",
        "mk-MK,mk;q=0.9",
        "ml-IN,ml;q=0.9",
        "mn-MN,mn;q=0.9",
        "mr-IN,mr;q=0.9",
        "ms-MY,ms;q=0.9",
        "mt-MT,mt;q=0.9",
        "my-MM,my;q=0.9",
        "nb-NO,nb;q=0.9",
        "ne-NP,ne;q=0.9",
        "nl-NL,nl;q=0.9",
        "nn-NO,nn;q=0.9",
        "or-IN,or;q=0.9",
        "pa-IN,pa;q=0.9",
        "pl-PL,pl;q=0.9",
        "pt-BR,pt;q=0.9",
        "pt-PT,pt;q=0.9",
        "ro-RO,ro;q=0.9",
        "ru-RU,ru;q=0.9",
        "si-LK,si;q=0.9",
        "sk-SK,sk;q=0.9",
        "sl-SI,sl;q=0.9",
        "sq-AL,sq;q=0.9",
        "sr-Cyrl-RS,sr;q=0.9",
        "sr-Latn-RS,sr;q=0.9",
        "sv-SE,sv;q=0.9",
        "sw-KE,sw;q=0.9",
        "ta-IN,ta;q=0.9",
        "te-IN,te;q=0.9",
        "th-TH,th;q=0.9",
        "tr-TR,tr;q=0.9",
        "uk-UA,uk;q=0.9",
        "ur-PK,ur;q=0.9",
        "uz-Latn-UZ,uz;q=0.9",
        "vi-VN,vi;q=0.9",
        "zh-CN,zh;q=0.9",
        "zh-HK,zh;q=0.9",
        "zh-TW,zh;q=0.9",
        "am-ET,am;q=0.8",
        "as-IN,as;q=0.8",
        "az-Cyrl-AZ,az;q=0.8",
        "bn-BD,bn;q=0.8",
        "bs-Cyrl-BA,bs;q=0.8",
        "bs-Latn-BA,bs;q=0.8",
        "dz-BT,dz;q=0.8",
        "fil-PH,fil;q=0.8",
        "fr-CA,fr;q=0.8",
        "fr-CH,fr;q=0.8",
        "fr-BE,fr;q=0.8",
        "fr-LU,fr;q=0.8",
        "gsw-CH,gsw;q=0.8",
        "ha-Latn-NG,ha;q=0.8",
        "hr-BA,hr;q=0.8",
        "ig-NG,ig;q=0.8",
        "ii-CN,ii;q=0.8",
        "is-IS,is;q=0.8",
        "jv-Latn-ID,jv;q=0.8",
        "ka-GE,ka;q=0.8",
        "kkj-CM,kkj;q=0.8",
        "kl-GL,kl;q=0.8",
        "km-KH,km;q=0.8",
        "kok-IN,kok;q=0.8",
        "ks-Arab-IN,ks;q=0.8",
        "lb-LU,lb;q=0.8",
        "ln-CG,ln;q=0.8",
        "mn-Mong-CN,mn;q=0.8",
        "mr-MN,mr;q=0.8",
        "ms-BN,ms;q=0.8",
        "mt-MT,mt;q=0.8",
        "mua-CM,mua;q=0.8",
        "nds-DE,nds;q=0.8",
        "ne-IN,ne;q=0.8",
        "nso-ZA,nso;q=0.8",
        "oc-FR,oc;q=0.8",
        "pa-Arab-PK,pa;q=0.8",
        "ps-AF,ps;q=0.8",
        "quz-BO,quz;q=0.8",
        "quz-EC,quz;q=0.8",
        "quz-PE,quz;q=0.8",
        "rm-CH,rm;q=0.8",
        "rw-RW,rw;q=0.8",
        "sd-Arab-PK,sd;q=0.8",
        "se-NO,se;q=0.8",
        "si-LK,si;q=0.8",
        "smn-FI,smn;q=0.8",
        "sms-FI,sms;q=0.8",
        "syr-SY,syr;q=0.8",
        "tg-Cyrl-TJ,tg;q=0.8",
        "ti-ER,ti;q=0.8",
        "tk-TM,tk;q=0.8",
        "tn-ZA,tn;q=0.8",
        "tt-RU,tt;q=0.8",
        "ug-CN,ug;q=0.8",
        "uz-Cyrl-UZ,uz;q=0.8",
        "ve-ZA,ve;q=0.8",
        "wo-SN,wo;q=0.8",
        "xh-ZA,xh;q=0.8",
        "yo-NG,yo;q=0.8",
        "zgh-MA,zgh;q=0.8",
        "zu-ZA,zu;q=0.8",
    ],
    encodingHeader: [
        "gzip, deflate, br",
        "deflate",
        "gzip, deflate, lzma, sdch",
        "deflate"
    ],
    controlHeader: [
        "no-cache",
        "max-age=0",
        "no-store",
        "no-transform",
        "only-if-cached",
        "must-revalidate",
        "public",
        "private",
        "proxy-revalidate",
        "s-maxage=86400"
    ],
    refers: [
        "https://www.google.com/",
        "https://www.facebook.com/",
        "https://www.twitter.com/",
        "https://www.youtube.com/",
        "https://www.linkedin.com/",
        "https://proxyscrape.com/",
        "https://www.instagram.com/",
        "https://wwww.reddit.com/",
        "https://fivem.net/",
        "https://www.fbi.gov/",
        "https://nettruyenplus.com/",
        "https://vnexpress.net/",
        "https://zalo.me",
        "https://shopee.vn",
        "https://www.tiktok.com/",
        "https://google.com.vn/",
        "https://tuoitre.vn/",
        "https://thanhnien.vn/",
        "https://nettruyento.com/",
        "https://www.google.com/search?q=",
        "https://check-host.net/",
        "https://www.facebook.com/",
        "https://www.youtube.com/",
        "https://www.fbi.com/",
        "https://www.bing.com/search?q=",
        "https://r.search.yahoo.com/",
        "https://www.cia.gov/index.html",
        "https://vk.com/profile.php?redirect=",
        "https://www.usatoday.com/search/results?q=",
        "https://help.baidu.com/searchResult?keywords=",
        "https://steamcommunity.com/market/search?q=",
        "https://www.ted.com/search?q=",
        "https://play.google.com/store/search?q=",
        "https://www.qwant.com/search?q=",
        "https://soda.demo.socrata.com/resource/4tka-6guv.json?$q=",
        "https://www.google.ad/search?q=",
        "https://www.google.ae/search?q=",
        "https://www.google.com.af/search?q=",
        "https://www.google.com.ag/search?q=",
        "https://www.google.com.ai/search?q=",
        "https://www.google.al/search?q=",
        "https://www.google.am/search?q=",
        "https://www.google.co.ao/search?q=",
        "http://anonymouse.org/cgi-bin/anon-www.cgi/",
        "http://coccoc.com/search#query=",
        "http://ddosvn.somee.com/f5.php?v=",
        "http://engadget.search.aol.com/search?q=",
        "http://engadget.search.aol.com/search?q=query?=query=&q=",
        "http://eu.battle.net/wow/en/search?q=",
        "http://filehippo.com/search?q=",
        "http://funnymama.com/search?q=",
        "http://go.mail.ru/search?gay.ru.query=1&q=?abc.r&q=",
        "http://go.mail.ru/search?gay.ru.query=1&q=?abc.r/",
        "http://go.mail.ru/search?mail.ru=1&q=",
        "http://help.baidu.com/searchResult?keywords=",
        "http://host-tracker.com/check_page/?furl=",
        "http://itch.io/search?q=",
        "http://jigsaw.w3.org/css-validator/validator?uri=",
        "http://jobs.bloomberg.com/search?q=",
        "http://jobs.leidos.com/search?q=",
        "http://jobs.rbs.com/jobs/search?q=",
        "http://king-hrdevil.rhcloud.com/f5ddos3.html?v=",
        "http://louis-ddosvn.rhcloud.com/f5.html?v=",
        "http://millercenter.org/search?q=",
        "http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0&q=",
        "http://nova.rambler.ru/search?=btnG?=%D0?2?%D0?2?%=D0/",
        "http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B&q=",
        "http://nova.rambler.ru/search?btnG=%D0%9D%?D0%B0%D0%B/",
        "http://page-xirusteam.rhcloud.com/f5ddos3.html?v=",
        "http://php-hrdevil.rhcloud.com/f5ddos3.html?v=",
        "http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x&q=",
        "http://ru.search.yahoo.com/search;?_query?=l%t=?=?A7x/",
        "http://ru.search.yahoo.com/search;_yzt=?=A7x9Q.bs67zf&q="
    ],
    userAgent: [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.94 Chrome/37.0.2062.94 Safari/537.36",
        "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
        "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
        "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9",
        "Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4",
        "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240",
        "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
        "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko",
        "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
        "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko",
        "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
        "Mozilla/5.0 (Linux; Android 12; V2120 Build/SP1A.210812.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36",
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
        'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0',
        'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edge/12.0',
        'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
        "Mozilla/5.0 (Linux; Android 6.0.1; SM-G532MT) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36"
    ],
    version: [
        '"Chromium";v="100", "Google Chrome";v="100"',
        '"(Not(A:Brand";v="8", "Chromium";v="98"',
        '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
        '"Not_A Brand";v="8", "Google Chrome";v="109", "Chromium";v="109"',
        '"Not_A Brand";v="99", "Google Chrome";v="86", "Chromium";v="86"',
        '"Not_A Brand";v="99", "Google Chrome";v="96", "Chromium";v="96"',
        '"Not A;Brand";v="99", "Chromium";v="96", "Microsoft Edge";v="96"'
    ],
    platform: [
        //'Linux',
        //'macOS',
        'Windows'
    ],
    site: [
        'cross-site',
        'same-origin',
        'same-site',
        'none'
    ],
    mode: [
        'cors',
        'navigate',
        'no-cors',
        'same-origin'
    ],
    dest: [
        'document',
        'image',
        'embed',
        'empty',
        'frame'
    ],
    rateHeaders: rateHeadersGenerator(1),
    rateHeaders2: rateHeadersGenerator(2),
    userAgentL: [
        '(CheckSecurity 2_0)',
        '(BraveBrowser 5_0)',
        '(ChromeBrowser 3_0)',
        '(ChromiumBrowser 4_0)',
        '(AtakeBrowser 2_0)',
        '(NasaChecker)',
        '(CloudFlareIUAM)',
        '(NginxChecker)',
        '(AAPanel)',
        '(AntiLua)',
        '(FushLua)',
        '(FBIScan)',
        '(FirefoxTop)',
        '(ChinaNet Bot)'
    ],
    mozilla: [
        'Mozilla/5.0 ',
        'Mozilla/6.0 ',
        'Mozilla/7.0 ',
        'Mozilla/8.0 ',
        'Mozilla/9.0 '
    ]
};

function generateRecipes() {
    const recipe = {
        cipher: randomElement(recipeList.cipher),
        sigAlgorithm: randomElement(recipeList.sigAlgorithm),
        userAgent: randomElement(recipeList.userAgent),
        version: randomElement(recipeList.version),
        userAgentL: randomElement(recipeList.userAgentL),
        platform: randomElement(recipeList.platform),
        refers: randomElement(recipeList.refers),
        site: randomElement(recipeList.site),
        mozilla: randomElement(recipeList.mozilla),
        mode: randomElement(recipeList.mode),
        dest: randomElement(recipeList.dest),
        acceptHeader: randomElement(recipeList.acceptHeader),
        langHeader: randomElement(recipeList.langHeader),
        encodingHeader: randomElement(recipeList.encodingHeader),
        controlHeader: randomElement(recipeList.controlHeader),
    };

    return recipe;
}

function generateHeaders(parsedUrl = new URL("https://google.com")) {
    const headers = {
        ":method": "POST",
        ":authority": parsedUrl.host + ":443",
        "x-forwarded-proto": "https",
        ":path": parsedUrl.pathname + "?" + randstr(6) + "=" + randstr(15),
        ":scheme": "https",
        "origin": parsedUrl.origin + ":443",
        "referer": parsedUrl.href,
        "Via": "1.1 " + parsedUrl.host + ":443",
        "cluster-ip": randstr(5)
    };

    return headers;
}

module.exports = { generateHeaders, generateRecipes };